POST http://localhost:8000/api/login
Accept: application/json

{
"username": "musa@cs.kg",
"password": "123123"
}
> {%
    client.global.set("auth_token", response.body.token);
%}

###

GET http://localhost:8000/api/dashboard
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8000/api/store
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
"name":"",
"email":"test@test.ts",
"phone":"4534534545",
"address":"dsfsdfsd, 45"
}
